### PR TITLE
add two evm transfer api

### PR DESCRIPTION
**Pull request by Frankonly**

### CODE REVIEW

**Comment by Frankonly** [comment]
@lizhefeng pls help review

**Comment by yutongp** [comment]
is that possible to change your editor config to not change the file format?

**Review by lizhefeng — COMMENTED** [review]
What is your protoc version?

**Comment by Frankonly** [comment]
> What is your protoc version?

3.11.3

**Comment by Frankonly** [comment]
> is that possible to change your editor config to not change the file format?

Do you mean indentation？I found code blocks in one file use different size of indentation, so I choose one of them and reformat the file.

**Pull request closed without merging**
